### ISSUE TITLE
Example not working - Cannot find variable `examples`

### ISSUE THREAD

**Issue by pietro909** [NoRedInk/json-elm-schema#31] opened 2017-12-14 07:21 UTC
When I try to build with `elm-make Main.elm` (or elm-reactor), I get:

```
-- NAMING ERROR ------------------------------------------------------- Main.elm

Cannot find variable `examples`

19|                     , examples Encode.int [ 5, 50 ]
                          ^^^^^^^^


-- NAMING ERROR ------------------------------------------------------- Main.elm

Cannot find variable `examples`

27|         , examples Encode.object
              ^^^^^^^^
```

**Comment by jwoudenberg** [comment] 2017-12-14 07:34
Thanks for reporting! It looks like the json schema version in the 'examples' directory was pretty old. I just pushed a fix to address that. If you pull in that fix and reinstall packages in the `examples/` directory you should be good! Let me know if you run into further issues!

**Comment by pietro909** [comment] 2017-12-14 08:23
Hi, I've done this:

- git pull
- move to ./examples
- remove elm-stuff
- start elm-reactor

Now I get a blank page (it builds), and in the console I have:

    Uncaught TypeError: runElmProgram is not a function
    at Main.elm:10

Strange, it is the first time I experiment this.

**Comment by jwoudenberg** [comment] 2017-12-14 09:40
Weird :/, I can reproduce this as well using elm-reactor. I think it might be that elm-reactor doesn't support a 'headless program', like the one exported by the example: It's a program that doesn't have a view function and only communicates over ports.

Either way it looks to be a more general issue, not specifically related to elm-json-schema. See here: https://github.com/elm-lang/elm-platform/issues/186

It might be easier to run `elm-make` on the `Main.elm` file directly, which does seem to work for me.

**Comment by pietro909** [comment] 2017-12-14 09:50
Thanks! We can close this from my side as it's not related to this repo :-)

**Closed** 2017-12-14 10:20 UTC
